# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('maxAlumnos', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoInscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('I', 'Inscrito'), ('N', 'No inscrito')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('correoElectronico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoFinal', models.CharField(choices=[('A', 'Aprobado'), ('P', 'Pendiente'), ('R', 'Reprobado')], max_length=1)),
                ('notaFinal', models.IntegerField(default=1)),
                ('estadoInscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EstadoInscripcion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnosInscritos', models.IntegerField(default=50)),
                ('anio', models.CharField(max_length=4)),
                ('semestre', models.CharField(choices=[('1', 'Primer semestre'), ('2', 'Segundo Semestre')], max_length=1)),
                ('profesor', models.CharField(max_length=50)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaMalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignaturasAprobadas', models.IntegerField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Estudiante')),
                ('mallaCurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.MallaCurricular')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcionasignatura',
            name='instancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.InstanciaAsignatura'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='mallaCurricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.MallaCurricular'),
        ),
    ]
